config/routes.rb
Rails.application.routes.draw do

  # ADMIN SECTION ###########################
  get 'admin', :to => 'admin/admin#login'
  namespace :admin do

    get 'home', :to => 'admin#home', as: 'home'
    # authentication routes
    post 'access', :to => 'admin#access'
    get 'logout', :to => 'admin#logout'
    # configurations routes
    get 'configuration', :to => 'config#home', as: 'configuration'
    post'configuration/update_settings', :to => 'config#update_settings', as: 'config_settings'
    get 'configuration/generate_migration', :to => 'config#generate_migration', as: 'config_migrations'
    get 'configuration/guide', :to => 'config#guide', as: 'config_guide'
    get 'configuration/development', :to => 'config#development', as: 'config_development'
    get 'configuration/languages', :to => 'config#languages', as: 'config_languages'
    post 'configuration/languages/initialize', :to => 'config#languages_initialize', as: 'config_languages_initialize'
    # users
    resources :users
    # notes
    resources :notes
    # pages
    resources :pages
    #images
    resources :images
    # fields
    get 'fields/new_repeater', :to => 'fields#new_repeater', as: 'new_field_repeater'
    post 'fields/create_repeater', :to => 'fields#create_repeater', as: 'create_field_repeater'
    delete 'fields/remove-att/:id', :to => 'fields#remove_attachment', as: 'delete_field_attachment'
    resources :fields
    # types
    get '/type/:typename', :to => 'types#index_objects', as: 'index_type_objects'
    get '/type/:typename/show/:objectid', :to => 'types#show_objects', as: 'show_type_objects'
    get '/type/:typename/new', :to => 'types#new_objects', as: 'new_type_objects'
    post '/type/:typename/create', :to => 'types#create_objects', as: 'create_type_objects'
    get '/type/:typename/edit/:objectid', :to => 'types#edit_objects', as: 'edit_type_objects'
    patch '/type/:typename/update/:objectid', :to => 'types#update_objects', as: 'update_type_objects'
    delete '/type/:typename/delete/:objectid', :to => 'types#destroy_objects', as: 'delete_type_objects'
    delete '/type/remove-att/:tablename/:typeid/:typefieldname' => 'types#remove_attachment', as: 'delete_typefield_attachment'
    resources :types
    #typefields
    resources :typefields
  end
  ###########################################

  # TEMPLATE SECTION ########################

  if($gams_config['has_languages'] === 'true')
    scope "/:locale" do
      root 'template/template#homepage'
      match '/:url', :to => 'template/template#routes', via: :get
      match '/:url/:id', :to => 'template/template#routes', via: :get
    end
  else
      root 'template/template#homepage'
      match '/:url', :to => 'template/template#routes', via: :get
      match '/:url/:id', :to => 'template/template#routes', via: :get
  end

  ###########################################

end

app/models/field.rb
class Field < ActiveRecord::Base

  before_save {
    self.name = self.name.downcase
    self.name = self.name.parameterize('_')
  }

  belongs_to :pages

  FIELD_LIST = %w(text textarea number editor image repeater)

  validates_uniqueness_of :name, :scope => :page_id
  validates_inclusion_of :type_field, :presence => true, :in => FIELD_LIST

  # Traco
  translates :value

end

app/controllers/admin/fields_controller.rb
class Admin::FieldsController < Admin::AdminController
  before_action :control_user
  before_action :control_editor, only: [:remove_attachment]
  before_action :control_admin, only: [:new, :create, :new_repeater, :create_repeater]

  def index
    redirect_to admin_path
  end

  def show
    redirect_to admin_path
  end

  def new
    @pages = Page.all
  end

  def create
    @field = Field.new(type_field: params[:type], name: params[:name].downcase, title: params[:title], page_id: params[:page], position: params[:position])
    if (@field.save)
      # output
      flash[:success] = $language['field_saved']
    else
      # output
      flash[:danger] = $language['field_not_saved']
      error_list = ""
      @field.errors.full_messages.each do |error|
        error_list += " #{error}, "
      end
      flash[:warning] = error_list[0...-2]
    end
    redirect_to admin_configuration_path
  end

  def edit
    redirect_to admin_path
  end

  def update
    redirect_to admin_path
  end

  def destroy
    redirect_to admin_path
  end

  def new_repeater
    @pages = Page.all
    @types = Type.all
  end

  def create_repeater
    @field = Field.new(type_field: params[:type], name: params[:name].downcase, title: params[:title], page_id: params[:page], repeating: params[:repeating], position: params[:position])
    if (@field.save)
      # output
      flash[:success] = $language['field_saved']
    else
      # output
      flash[:danger] = $language['field_not_saved']
      error_list = ""
      @field.errors.full_messages.each do |error|
        error_list += " #{error}, "
      end
      flash[:warning] = error_list[0...-2]
    end
    redirect_to admin_configuration_path
  end

end

app/views/admin/fields/new.html.erb
<% provide(:title, "#{$language['new'].capitalize} #{$language['field_singular']}") %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:title) %></h3>
  </div>
  <div class="panel-body">
    <%= form_tag(admin_fields_path, method: "post", multipart: true, action: :create) do %>

    <div class="col-md-6 col-lg-6">
      <h4 class="field-title"><%= $language['name'].capitalize %></h4>
      <div class="input-group">
        <label class="input-group-addon"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></label>
        <input class="form-control" type="text"  name="name">
      </div>
      <br>
    </div>

    <div class="col-md-6 col-lg-6">
      <h4 class="field-title"><%= $language['title'].capitalize %></h4>
      <div class="input-group">
        <label class="input-group-addon"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></label>
        <input class="form-control" type="text"  name="title">
      </div>
      <br>
    </div>

    <div class="col-md-4 col-lg-4">
      <h4 class="field-title"><%= $language['field_type'].capitalize %></h4>
      <select class="selectpicker" name="type" data-live-search="true">
        <option value="text"><%= $language['text'].capitalize %></option>
        <option value="number"><%= $language['number'].capitalize %></option>
        <option value="textarea"><%= $language['textarea'].capitalize %></option>
        <option value="editor"><%= $language['editor'].capitalize %></option>
        <option value="image"><%= $language['image'].capitalize %></option>
      </select>
      <br>
    </div>

    <div class="col-md-4 col-lg-4">
      <h4 class="field-title"><%= $language['page_singular'].capitalize %></h4>
      <select class="selectpicker" name="page" data-live-search="true">
        <% @pages.each do |page| %>
          <option value="<%= page.id %>"><%= page.title %></option>
        <% end %>
      </select>
      <br>
    </div>

    <div class="col-md-4 col-lg-4">
      <h4 class="field-title"><%= $language['position'].capitalize %></h4>
      <div class="input-group">
        <label class="input-group-addon"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></label>
        <input class="form-control" type="number"  name="position">
      </div>
      <br>
    </div>

    <div class="col-md-12 col-lg-12">
      <input class="btn btn-primary" type="submit" value="<%= $language['save'].capitalize %>">
    </div>

    <% end %>
  </div>
</div>

app/views/admin/fields/new_repeater.html.erb
<% provide(:title, "#{$language['new'].capitalize} #{$language['field_repeater_singular']}") %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:title) %></h3>
  </div>
  <div class="panel-body">
    <%= form_tag(admin_create_field_repeater_path, method: "post", multipart: true, action: :create_repeater) do %>

    <input type="hidden" name="type" value="repeater">

    <div class="col-md-6 col-lg-6">
      <h4 class="field-title"><%= $language['name'].capitalize %></h4>
      <div class="input-group">
        <label class="input-group-addon"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></label>
        <input class="form-control" type="text"  name="name">
      </div>
      <br>
    </div>

    <div class="col-md-6 col-lg-6">
      <h4 class="field-title"><%= $language['title'].capitalize %></h4>
      <div class="input-group">
        <label class="input-group-addon"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></label>
        <input class="form-control" type="text"  name="title">
      </div>
      <br>
    </div>

    <div class="col-md-4 col-lg-4">
      <h4 class="field-title"><%= $language['field_repeater_of'] %></h4>
      <select class="selectpicker" name="repeating" data-live-search="true">
        <% @types.each do |type| %>
          <option value="<%= type.name %>"><%= type.title_p.capitalize %></option>
        <% end %>
      </select>
      <br>
    </div>


    <div class="col-md-4 col-lg-4">
      <h4 class="field-title"><%= $language['page_singular'].capitalize %></h4>
      <select class="selectpicker" name="page" data-live-search="true">
        <% @pages.each do |page| %>
          <option value="<%= page.id %>"><%= page.title %></option>
        <% end %>
      </select>
      <br>
    </div>

    <div class="col-md-4 col-lg-4">
      <h4 class="field-title"><%= $language['position'].capitalize %></h4>
      <div class="input-group">
        <label class="input-group-addon"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></label>
        <input class="form-control" type="number"  name="position">
      </div>
      <br>
    </div>

    <div class="col-md-12 col-lg-12">
      <input class="btn btn-primary" type="submit" value="<%= $language['save'].capitalize %>">
    </div>

    <% end %>
  </div>
</div>