config/routes.rb
Rails.application.routes.draw do

  # ADMIN SECTION ###########################
  get 'admin', :to => 'admin/admin#login'
  namespace :admin do

    get 'home', :to => 'admin#home', as: 'home'
    # authentication routes
    post 'access', :to => 'admin#access'
    get 'logout', :to => 'admin#logout'
    # configurations routes
    get 'configuration', :to => 'config#home', as: 'configuration'
    post'configuration/update_settings', :to => 'config#update_settings', as: 'config_settings'
    get 'configuration/generate_migration', :to => 'config#generate_migration', as: 'config_migrations'
    get 'configuration/guide', :to => 'config#guide', as: 'config_guide'
    get 'configuration/development', :to => 'config#development', as: 'config_development'
    get 'configuration/languages', :to => 'config#languages', as: 'config_languages'
    post 'configuration/languages/initialize', :to => 'config#languages_initialize', as: 'config_languages_initialize'
    # users
    resources :users
    # notes
    resources :notes
    # pages
    resources :pages
    #images
    resources :images
    # fields
    get 'fields/new_repeater', :to => 'fields#new_repeater', as: 'new_field_repeater'
    post 'fields/create_repeater', :to => 'fields#create_repeater', as: 'create_field_repeater'
    delete 'fields/remove-att/:id', :to => 'fields#remove_attachment', as: 'delete_field_attachment'
    resources :fields
    # types
    get '/type/:typename', :to => 'types#index_objects', as: 'index_type_objects'
    get '/type/:typename/show/:objectid', :to => 'types#show_objects', as: 'show_type_objects'
    get '/type/:typename/new', :to => 'types#new_objects', as: 'new_type_objects'
    post '/type/:typename/create', :to => 'types#create_objects', as: 'create_type_objects'
    get '/type/:typename/edit/:objectid', :to => 'types#edit_objects', as: 'edit_type_objects'
    patch '/type/:typename/update/:objectid', :to => 'types#update_objects', as: 'update_type_objects'
    delete '/type/:typename/delete/:objectid', :to => 'types#destroy_objects', as: 'delete_type_objects'
    delete '/type/remove-att/:tablename/:typeid/:typefieldname' => 'types#remove_attachment', as: 'delete_typefield_attachment'
    resources :types
    #typefields
    resources :typefields
  end
  ###########################################

  # TEMPLATE SECTION ########################

  if($gams_config['has_languages'] === 'true')
    scope "/:locale" do
      root 'template/template#homepage'
      match '/:url', :to => 'template/template#routes', via: :get
      match '/:url/:id', :to => 'template/template#routes', via: :get
    end
  else
      root 'template/template#homepage'
      match '/:url', :to => 'template/template#routes', via: :get
      match '/:url/:id', :to => 'template/template#routes', via: :get
  end

  ###########################################

end

app/views/layouts/admin/_footer.html.erb
<div class="text-right">
  <a href="<%= $gams_config['footer_url'] %>"><%= $gams_config['footer_text'] %></a>
</div>

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to $gams_config['header_text'], root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if (session[:user]) %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to $language['header_logout'], admin_logout_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to $language['header_website'], root_path %></li>
            <li><%= link_to $language['header_dashboard'], admin_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <% end %>
  </div><!-- /.container-fluid -->
</header>

app/views/layouts/admin/_menu.html.erb
<div class="panel panel-primary" id="partial-menu">
  <div class="panel-heading" data-toggle="collapse" href="#menu-collapse" aria-expanded="true" aria-controls="menu-collapse">
    <h3 class="panel-title">
      <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
      Menu
    </h3>
  </div>
  <div class="list-group collapse" id="menu-collapse">
    <a href="<%= admin_home_path %>" class="list-group-item <%= setActive(admin_home_path) %>">
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      <%= $language['menu_home'] %>
    </a>
    <a href="<%= admin_users_path %>" class="list-group-item <%= setActive(admin_users_path) %>">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
      <%= $language['menu_users'] %>
    </a>
    <a href="<%= admin_pages_path %>" class="list-group-item <%= setActive(admin_pages_path) %>">
      <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
      <%= $language['menu_pages'] %>
    </a>

    <% # List of sites custom types %>
    <% types = Type.where(visible: true).order('title_p DESC') %>

    <% types.each do |type| %>
      <a href="<%= admin_index_type_objects_path(type.name) %>" class="list-group-item <%= setActive(admin_types_path(type.name)) %>">
        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
        <%= type.title_p.capitalize %>
        <span class="badge"><%= type.name.capitalize.constantize.count %></span>
      </a>
    <% end %>
    <% # End of the list %>

    <a href="<%= admin_images_path %>" class="list-group-item <%= setActive(admin_images_path) %>">
      <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
      <%= $language['menu_images'] %>
    </a>

    <a href="<%= admin_notes_path %>" class="list-group-item <%= setActive(admin_notes_path) %>">
      <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
      <%= $language['menu_notes'] %>
    </a>

    <% # Show settings link only to administrator users %>
    <% if(session[:user_permissions] and session[:user_permissions] === 0) %>
    <a href="<%= admin_configuration_path %>" class="list-group-item <%= setActive(admin_configuration_path) %>">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      <%= $language['menu_configuration'] %>
    </a>
    <% end %>

  </div>
</div>

<script>

// SET MENU VISIBLE ON DESKTOP
if(window.innerWidth > 991) {
  $('#menu-collapse').addClass('in');
}
</script>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Admin</title>
  <%= stylesheet_link_tag    "admin/admin", :media => "all" %>
  <%= javascript_include_tag "admin/admin" %>
</head>
<body style="padding-top: 70px">

<% if (session[:user]) %>
  <%= render 'layouts/admin/header' %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%= msg_type %>"><%= msg %></div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% if (session[:user]) %>
      <div class="col-md-4 col-lg-3">
        <%= render 'layouts/admin/menu' %>
      </div>
      <div class="col-md-8 col-lg-9">
        <%= yield %>
        <%= render 'layouts/admin/footer' %>
      </div>
    <% else %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-sm-offset-4 col-lg-offset-4">
        <%= yield %>
      </div>
    <% end %>
  </div>
</div>

</body>
</html>