config/routes.rb
Rails.application.routes.draw do

  # ADMIN SECTION ###########################
  get 'admin', :to => 'admin/admin#login'
  namespace :admin do

    get 'home', :to => 'admin#home', as: 'home'
    # authentication routes
    post 'access', :to => 'admin#access'
    get 'logout', :to => 'admin#logout'
    # configurations routes
    get 'configuration', :to => 'config#home', as: 'configuration'
    post'configuration/update_settings', :to => 'config#update_settings', as: 'config_settings'
    get 'configuration/generate_migration', :to => 'config#generate_migration', as: 'config_migrations'
    get 'configuration/guide', :to => 'config#guide', as: 'config_guide'
    get 'configuration/development', :to => 'config#development', as: 'config_development'
    get 'configuration/languages', :to => 'config#languages', as: 'config_languages'
    post 'configuration/languages/initialize', :to => 'config#languages_initialize', as: 'config_languages_initialize'
    # users
    resources :users
    # notes
    resources :notes
    # pages
    resources :pages
    #images
    resources :images
    # fields
    get 'fields/new_repeater', :to => 'fields#new_repeater', as: 'new_field_repeater'
    post 'fields/create_repeater', :to => 'fields#create_repeater', as: 'create_field_repeater'
    delete 'fields/remove-att/:id', :to => 'fields#remove_attachment', as: 'delete_field_attachment'
    resources :fields
    # types
    get '/type/:typename', :to => 'types#index_objects', as: 'index_type_objects'
    get '/type/:typename/show/:objectid', :to => 'types#show_objects', as: 'show_type_objects'
    get '/type/:typename/new', :to => 'types#new_objects', as: 'new_type_objects'
    post '/type/:typename/create', :to => 'types#create_objects', as: 'create_type_objects'
    get '/type/:typename/edit/:objectid', :to => 'types#edit_objects', as: 'edit_type_objects'
    patch '/type/:typename/update/:objectid', :to => 'types#update_objects', as: 'update_type_objects'
    delete '/type/:typename/delete/:objectid', :to => 'types#destroy_objects', as: 'delete_type_objects'
    delete '/type/remove-att/:tablename/:typeid/:typefieldname' => 'types#remove_attachment', as: 'delete_typefield_attachment'
    resources :types
    #typefields
    resources :typefields
  end
  ###########################################

  # TEMPLATE SECTION ########################

  if($gams_config['has_languages'] === 'true')
    scope "/:locale" do
      root 'template/template#homepage'
      match '/:url', :to => 'template/template#routes', via: :get
      match '/:url/:id', :to => 'template/template#routes', via: :get
    end
  else
      root 'template/template#homepage'
      match '/:url', :to => 'template/template#routes', via: :get
      match '/:url/:id', :to => 'template/template#routes', via: :get
  end

  ###########################################

end

app/models/image.rb
class Image < ActiveRecord::Base
  
  # Paperclip
  has_attached_file :image, styles: { medium: "800x800>", thumb: "250x250>" }
  validates_attachment 	:image, :presence => true, :content_type => { :content_type => /\Aimage\/.*\Z/ }, :size => { :less_than => 5.megabyte }

  # Traco
  translates :title
  translates :description

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::AdminController
  before_action :control_user

  def index
    @images = Image.paginate(:page => params[:page], :per_page => 12).order('created_at DESC')
    if(@question = Image.ransack(params[:q]))
      @images = @question.result.paginate(:page => params[:page], :per_page => 12).order('created_at DESC')
    end
  end

  def show
    @image = Image.find(params[:id])
    if(params[:locale])
      @title_field_name = "title_#{params[:locale]}"
      @description_field_name = "description_#{params[:locale]}"
    else
      @title_field_name = "title_#{I18n.default_locale}"
      @description_field_name = "description_#{I18n.default_locale}"
    end
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(params[:image].permit!)
    # Ajax update for images list
    if(@image.save)
      @images = Image.all.reverse
      respond_to do |format|
        format.js # Response not working
	    end
    end
  end

  def edit
    @image = Image.find(params[:id])
    if(params[:locale])
      @title_field_name = "title_#{params[:locale]}"
      @description_field_name = "description_#{params[:locale]}"
    else
      @title_field_name = "title_#{I18n.default_locale}"
      @description_field_name = "description_#{I18n.default_locale}"
    end
  end

  def update
    @image = Image.find(params[:id]) or redirect_to admin_path
    if @image.update(params[:image].permit(:title, :description))
      flash[:success] = $language['image_updated']
    else
      flash[:danger] = $language['image_not_updated']
      error_list = ""
      @image.errors.full_messages.each do |error|
        error_list += " #{error}, "
      end
      flash[:warning] = error_list[0...-2]
    end
    redirect_to admin_image_path(@image)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash[:success] = $language['image_deleted']
    redirect_to admin_images_path
  end

end

app/views/admin/images/create.js.erb
// This js is not working but necessary to make the CMS work

app/views/admin/images/edit.html.erb
<% provide(:title, "#{$language['edit'].capitalize} #{$language['image_singular'].capitalize}") %>

<div class="home panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:title) %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-12 col-lg-12 text-right">
      <%= getLanguageSelector() %>
    </div>
    <%= form_for [:admin, @image] do |f| %>
      <div class="col-md-8 col-lg-8">
        <h4 class="field-title"><%= $language['title'].capitalize %></h4>
        <div class="input-group">
          <label class="input-group-addon"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></label>
          <input class="form-control" type="text"  name="image[title]" value="<%= @image.send(@title_field_name) %>">
        </div>
        <br>
        <h4 class="field-title"><%= $language['description'].capitalize %></h4>
        <div class="input-group">
          <label class="input-group-addon"><span class="glyphicon glyphicon-font" aria-hidden="true"></label>
          <textarea class="form-control" type="text"  name="image[description]" style="height: 100px"><%= raw @image.send(@description_field_name) %></textarea>
        </div>
        <br>
      </div>
      <div class="col-md-4 col-lg-4">
        <div class="img-thumbnail media-content" style="background-image: url(<%= @image.image.url(:medium) %>)"></div>
      </div>
      <div class="col-md-12 col-lg-12">
        <input class="btn btn-primary" type="submit" value="<%= $language['save'].capitalize %>">
      </div>
    <% end %>
  </div>
</div>

app/views/admin/images/index.html.erb
<% provide(:title, $language['image_plural'].capitalize) %>

<div class="home panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:title) %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-6 col-lg-6">
      <div class="list-group">
      <%= search_form_for [:admin, @question] do |f| %>
        <div class="input-group">
          <%= f.search_field "title_#{I18n.default_locale}_cont", class: 'form-control', placeholder: $language['title'].capitalize %>
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default" type="button"><%= $language['search'].capitalize %></button>
          </span>
        </div><!-- /input-group -->
        <% end %>
      </div>
    </div>
    <div class="col-md-6 col-lg-6 text-right">
      <%= link_to $language['new'].capitalize, new_admin_image_path, class: "btn btn-primary" %>
      <br><br>
    </div>
    <% if(@images.length > 0) %>
      <% @images.each do |image| %>
        <div class="col-md-4 col-lg-4">
          <a href="<%= admin_image_path(image.id) %>" class="img-thumbnail media-content" style="background-image: url(<%= image.image.url(:medium) %>)"></a>
        </div>
      <% end %>
    <% else %>
    <div class="col-md-12 col-lg-12">
      <div class="alert alert-danger" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only"></span>
        <%= $language['image_not_found'].capitalize %>
      </div>
    </div>
    <% end %>

    <div class="col-md-12 col-lg-12">
      <div style="text-align: center" >
        <%= will_paginate @images, :renderer => BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/admin/images/new.html.erb
<% provide(:title, "#{$language['new'].capitalize} #{$language['image_singular']}") %>

<div class="home panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:title) %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-12 col-lg-12">
      <%= form_for([:admin, @image], :remote => true, :format => :js,  html: { multipart: true, class: "dropzone"}) do |f|  %>
        <div class="fallback">
          <%= f.file_field :file %><br>
          <%= f.submit "Upload file" %>
        </div>
      <% end %>
      <br>
    </div>

    <div class="col-md-12 col-lg-12 text-right">
      <%= link_to $language['back'].capitalize, admin_images_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<style>
/* Remove file name on dropzone */
.dz-filename {display: none;}
</style>

<script>
  $(document).ready(function(){
    // disable auto discover
    Dropzone.autoDiscover = false;

    var dropzone = new Dropzone (".dropzone", {
      maxFilesize: 5, // Set the maximum file size to 5MB
      paramName: "image[image]", // Rails expects the file upload to be something like model[field_name]
      addRemoveLinks: false, // Don't show remove links on dropzone itself.
      acceptedFiles: 'image/*',
      dictDefaultMessage: '<%=j raw $language['image_upload'] %>',
    });
  });
</script>

app/views/admin/images/show.html.erb
<% provide(:title, "#{$language['show'].capitalize} #{$language['image_singular'].capitalize}") %>

<div class="home panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= yield(:title) %></h3>
  </div>
  <div class="panel-body">
    <div class="col-md-12 col-lg-12 text-right">
      <%= getLanguageSelector() %>
    </div>
    <div class="col-md-8 col-lg-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= $language['title'].capitalize %></h3>
        </div>
        <div class="panel-body">
          <%= raw @image.send(@title_field_name) %>
        </div>
      </div>
      <br>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= $language['description'].capitalize %></h3>
        </div>
        <div class="panel-body">
          <%= raw @image.send(@description_field_name) %>
        </div>
      </div>
      <br>
    </div>
    <div class="col-md-4 col-lg-4">
      <div class="img-thumbnail media-content" style="background-image: url(<%= @image.image.url(:medium) %>)"></div>
    </div>
    <div class="col-md-12 col-lg-12">
      <%= link_to $language['edit'].capitalize, edit_admin_image_path(@image), class: "btn btn-info" %>
      <%= link_to $language['delete'].capitalize, admin_image_path(@image), :method => :delete, data: {confirm: $language['image_delete_confirmation']}, class: "btn btn-danger" %>
    </div>
  </div>
</div>